Feature/signin
winteryy/nbc_sns_team3 pull request #5
Opened 2024-04-02 03:12 UTC by lany159

로그인, 로그아웃 유효성 검사 추가

2024-04-02 06:25 UTC, winteryy requested changes
조금만 수정하면 엄청 좋아질 것 같네요, 고생하셨습니다!

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
>      }
메소드 따로 분리하신 시도가 좋습니다👍

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +        val isPw = inputUserPw.isEmpty()
아까 보여드린 것처럼, 초기화 시점의 값으로 고정됩니다.
말씀해주신 방법과 제안드린 방법 모두 좋은 솔루션이니 원하는 걸로 변경해보세요!

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +                return@setOnClickListener
string 리소스로 빼내신거 👍

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +            editor.putString("userPw",userPw.toString())
https://developer.android.com/training/data-storage/shared-preferences

아무래도 `SharedPreferences.Editor`를 통해서 변경점을 put하고 나면 `apply()` 또는 `commit()`을 통해 저장소에 저장해주는 것이 맞는 것 같습니다.
두 메소드의 차이점은 본문에 나와있는 것처럼 동기적인지 비동기적인지의 차이입니다.

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +    private lateinit var signUpPw :EditText
필요에 의해 지연 초기화 사용하신 게 좋네요!

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        val isPw = inputUserPw.isEmpty()
이미 알고 계신 듯 했지만, `SignInActivity`와 같이 초기화 시점에 값이 고정되는 로직입니다.

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        signUpPwText = findViewById<TextView>(R.id.signUpPwText)
View의 특정 attribute 값만 필요한 경우, 해당 값만을 변수로 둬도 무방할 것 같습니다.

예를 들자면,
```
//변경 전
 val signUpName = findViewById<EditText>(R.id.signUpName)
 val inputUserName = signUpName.text.toString()

//변경 후
 val inputUserName = findViewById<EditText>(R.id.signUpName).text.toString()
```

이런 식으로 불필요한 변수들을 줄일 수 있을 것 같아요. 물론 View 자체에도 쓰임새가 생길 예정이라면 그대로 두셔도 됩니다!

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +            finish()
아까 말씀드렸던건데, finish()가 유효성 검증의 결과와 관계없이 무조건 동작하고 있습니다!
그리고 비밀번호의 유효성 검증 결과가 영향을 미치지 못하고 있는 것으로 보입니다.

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        val pwdPattern = "^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@\$!%*#?&.])[A-Za-z[0-9]\$@\$!%*#?&.]{8,20}\$"
정규 표현식 이용하신거 아주 좋네요, 그런데 저희 비밀번호 길이 제한 5~10자로 하기로 하지 않았나요?

2024-04-02 06:25 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +            }
`afterTextChanged()`의 s값을 이용하면 `regularPw()`내에서 View에 접근해 텍스트를 가져오지 않고도, 현재 입력 중인 텍스트를 전달할 수 있을 것 같습니다.

2024-04-02 06:25 UTC, winteryy commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="text"
inputType이 "text"로 지정되어서, 비밀번호가 노출됩니다.☕

2024-04-02 06:47 UTC, lany159 commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        val pwdPattern = "^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@\$!%*#?&.])[A-Za-z[0-9]\$@\$!%*#?&.]{8,20}\$"
ㅋㅋㅋ맞네요...

2024-04-02 07:39 UTC, catandbutler reviewed
수고하셨습니다

2024-04-02 07:39 UTC, catandbutler commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +        val isPw = inputUserPw.isEmpty()
isEmpty 와 isblank 까먹고 있었는데 생각 났어요

2024-04-02 07:39 UTC, catandbutler commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        val pwdPattern = "^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@\$!%*#?&.])[A-Za-z[0-9]\$@\$!%*#?&.]{8,20}\$"
이게 그 특수문자 포함 패턴 인가요?

2024-04-02 07:52 UTC, lany159 commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        val pwdPattern = "^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@\$!%*#?&.])[A-Za-z[0-9]\$@\$!%*#?&.]{8,20}\$"
맞아요~ 정규식 표현 검색하면 제가 머리 안 써도 사람들이 리스트로 뽑아줘서 그대로 복붙! 마지막에 {5,10} <<여기가 길이 제한입니당

2024-04-02 07:55 UTC, lany159 commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="text"
눈으로 확인한다고 넣어뒀었는데 깜ㅃ...ㄱ..

2024-04-02 08:27 UTC, lany159 commented
안합칩니다~

2024-04-02 11:08 UTC, winteryy requested changes
몇 개만 더 고치면 될 거 같아요!!

2024-04-02 11:08 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +    private lateinit var signUpPw: EditText
`lateinit`으로 선언하셨는데, `signUpPw`가 초기화 이전에 호출되어 회원가입 액티비티 진입 시 앱이 죽는 것 같습니다😂

2024-04-02 11:08 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +                return@setOnClickListener
👍

2024-04-02 11:08 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +            }
비밀번호 `EditText`가 비어있는지는 검증하는데, 비밀번호가 올바른지는 검증하지 않고 있는 것 같습니다.
이미 검증하는 함수 잘 만들어두셨는데, 활용만 하시면 될 것 같습니다!

2024-04-02 11:08 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +            finish()
`finish()`가 여전히 유효성 검증의 결과와 관계 없이 동작합니다☕

2024-04-02 11:08 UTC, winteryy commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="text"
실수하신거 같은데 signUpID의 inputType을 "textPassword"로 변경하셨습니닷..

그리고 눈으로 확인할 때 다른 속성값에서 사용하신 것처럼, 
`tools:inputType="text"`로 지정하시면 실제 동작과는 관계 없이 인풋 타입이 "text"인 상태로 미리보기 할 수 있습니다!

2024-04-02 14:24 UTC, yoohyejeong commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +                return@setOnClickListener
안녕하세여 항상 응원하고 있습니당!

if (userId.text.isEmpty() ) {
    코드
}

부분에서 isEmpty() 가 빈 문자열을 확인하기 위해 사용된다는 사실을 알았습니다!

isEmpty와 isBlank() 둘다 사용가능한데

isEmpty는 "" 문자열인지 확인하고
isBlank는 비어있거나 공백으로 이루어져 있는지를 확인한대요

그래서 포괄적으로는 isBlank 메소드를 사용하면 문자열과 공백모두 확인할수있다고 하네요

덕분에 좋은 공부했습니다 감사합니다 :)

2024-04-02 14:32 UTC, yoohyejeong commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
> +        val inputUserPw = signUpPw.text.toString()
val 선언후 findViewById<weget>(R.id.idname) 으로 아이디를 변수에 담아주는것 잊지 않겠습니다!

2024-04-03 05:23 UTC, winteryy requested changes
화이팅!

2024-04-03 05:23 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
>              if (inputUserName.isEmpty() || inputUserId.isEmpty() || inputUserPw.isEmpty()) {
`inputUserName`에는 초기화 시점에 빈 값이 들어오게 되고(입력하는 `EditText`가 처음에 공란이므로), 이 조건식은 항상 true에 해당하게 됩니다.
같은 맥락으로 가져온 다른 변수 값들에도 똑같이 적용되는 부분입니다! 

그래서 아래처럼 값을 채워넣어도 if문에 걸리게 됩니다.
![image](https://github.com/winteryy/nbc_sns_team3/assets/104819764/f7b30d9d-76b8-4af8-8252-b4a6d4678486)

2024-04-03 05:23 UTC, winteryy commented on app/src/main/java/com/nbcteam3/nbcsns3/SignUpActivity.kt
>  }
👍

2024-04-03 05:23 UTC, winteryy commented on app/src/main/res/layout/activity_sign_up.xml
>          android:inputType="text"
아직 inputType이 "text"네요
![image](https://github.com/winteryy/nbc_sns_team3/assets/104819764/01596930-d918-414e-84f5-898afbbb3eff)

2024-04-03 08:29 UTC, catandbutler reviewed
수고하셨습니다!!!!!!!

2024-04-03 08:29 UTC, catandbutler commented on app/src/main/java/com/nbcteam3/nbcsns3/SignInActivity.kt
> +            if (userPw.text.isEmpty()) {
리턴 값 신기하네요!

2024-04-03 08:34 UTC, winteryy approved these changes
굳!

2024-04-03 08:34 UTC, catandbutler approved these changes
와!!!!

2024-04-03 08:46 UTC, yoohyejeong approved these changes
왕따봉

2024-04-03 08:47 UTC, merged